### ISSUE TITLE
Guides form instructions call out a checkbox that doesn't exist

### ISSUE THREAD

**Issue by rjsparks** [rjsparks/ietf-guides#3]
Right now the guides data entry form has instructions that say `If above you marked you're willing to be a guide at future meetings, we will keep your information to avoid you having to retype it next time.  Don't select this checkbox if you'd rather we erase your participation information between IETFs.`

But there is no such checkbox on the form.

**Comment by hardaker** [comment]
Thanks; I had forgotten about that.  I think we may just drop it this time around.  But in the long run, I'd like to not flush *all* the data if they agree to keep it around.
